version: "3.8"
services:
  php:
    build:
      context: ./
      dockerfile: docker/php/develop/Dockerfile
    ports:
      - "8080:8080"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./:/var/www/laravel
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/localhost.crt:/etc/nginx/localhost.crt
      - ./docker/nginx/localhost.key:/etc/nginx/localhost.key
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    image: mysql:8
    restart: always
